name: Send Patch Notes to Subscribers

on:
  release:
    types: [published]

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare and Send Patch Notes
        env:
          PATCH_NOTES_RAW: ${{ github.event.release.body }}
          BACKEND_URL: https://control-app-backend-aqm1.onrender.com/api/admin/send-patch-notes
        run: |
          # Convert newlines to <br> and encode as a JSON string
          PATCH_NOTES=$(echo "$PATCH_NOTES_RAW" | awk '{ printf "%s<br>", $0 }' | jq -Rs .)

          echo "Sending the following PATCH_NOTES:"
          echo "$PATCH_NOTES"

          curl -X POST "$BACKEND_URL" \
            -H "Content-Type: application/json" \
            -H "X-API-KEY: ${{ secrets.ADMIN_API_KEY }}" \
            -d "{\"notes\": $PATCH_NOTES}"
