name: Send Patch Notes to Subscribers

on:
  release:
    types: [published, edited]
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Patch Notes to Backend
        run: |
          PATCH_NOTES=$(echo "${{ github.event.release.body }}" | jq -Rs .)
          curl -X POST "$BACKEND_URL" \
            -H "Content-Type: application/json" \
            -H "X-API-KEY: ${{ secrets.ADMIN_API_KEY }}" \
            -d "{\"notes\": $PATCH_NOTES}"
        env:
          BACKEND_URL: https://control-app-backend-aqm1.onrender.com/api/admin/send-patch-notes

